### ISSUE TITLE
Persistent Storage S3 fails for Secrets Referencing 

### ISSUE THREAD

**Issue by samedguener** [armory/spinnaker-operator#136]
Hi all,

we are using the operator in version `1.0.0` and the open source Spinnaker installation in version `1.20.4`.

we are currently referencing secrets from Kubernetes as follow:

```yaml
  spinnakerConfig:
    # spec.spinnakerConfig.config - This section contains the contents of a deployment found in a halconfig .deploymentConfigurations[0]
    config:
      version: 1.20.4   # the version of Spinnaker to be deployed
      persistentStorage:
        persistentStoreType: s3
        s3:
          rootFolder: front50
          bucket: encrypted:k8s!n:spin-secrets!k:s3-bucket-name # Change to a unique name. Spinnaker stores application and pipeline definitions here
          region: encrypted:k8s!n:spin-secrets!k:s3-region
          accessKeyId: encrypted:k8s!n:spin-secrets!k:s3-access-key
          secretAccessKey: encrypted:k8s!n:spin-secrets!k:s3-secret-key
```

This is picked up by front50 as following in the pod:

```yaml
    Environment:
      JAVA_OPTS:                            -XX:MaxRAMPercentage=50.0
      FRONT50_SPIN_SECRETS_S3_REGION:       <set to the key 's3-region' in secret 'spin-secrets'>       Optional: false
      FRONT50_SPIN_SECRETS_S3_ACCESS_KEY:   <set to the key 's3-access-key' in secret 'spin-secrets'>   Optional: false
      FRONT50_SPIN_SECRETS_S3_BUCKET_NAME:  <set to the key 's3-bucket-name' in secret 'spin-secrets'>  Optional: false
      AWS_ACCESS_KEY_ID:                    encrypted:k8s!n:spin-secrets!k:s3-access-key
      AWS_SECRET_ACCESS_KEY:                <set to the key 's3-secret-key' in secret 'spin-secrets'>  Optional: false
      FRONT50_SPIN_SECRETS_S3_SECRET_KEY:   <set to the key 's3-secret-key' in secret 'spin-secrets'>  Optional: false
```

It seems like this line 
```yaml
      AWS_ACCESS_KEY_ID:                    encrypted:k8s!n:spin-secrets!k:s3-access-key
```
is wrong as the access key is not referenced from the secret `spin-secrets`.

This leads to following error of front50:
```
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: xx; S3 Extended Request ID: xx)
```

When we specify the access key directly in our `spinnakerConfig`, the bucket is created/used correctly any everything works.

Best,
Samed

P.S: Are here any guidelines for contributions/issues such as format?
