### ISSUE TITLE
Secrets engine is not rendered within Sidecars

### ISSUE THREAD

**Issue by dhurng** [armory/spinnaker-operator#139]
Sidecar configuration does not support:

Environment variables interpolated from Configmap (valuesFrom)
Key:Value secret rendering where Value if set to encrypted secret from Spinnaker, does not render properly.
ex. {{/GIT_SYNC_PASSWORD: encrypted:k8s!n:spinnaker-github-token!k:token/}}
Please let me know if you need further information. Thank you

**Comment by ncknt** [comment]
@dhurng would you have an example of this in a `SpinnakerService`? I am not sure how you're trying to use the `encrypted:k8s` notation. It is only meant to be used under `spec.spinnakerConfig.config` and `spec.spinnakerConfig.profiles`.

**Comment by tianhao0211** [comment]
Hey Nico, this is from David's updates, service would be a sidecar as shown here:

```sidecars:
spin-rosco:
- name: github-sync
dockerImage: k8s.gcr.io/git-sync:v3.1.1
mountPath: /opt/rosco/config/packer_custom
securityContext:
privileged: true
# waiting for known issue with encryption here

env:
GIT_SYNC_REPO: https://github.com/einsteinplatform/bakeshop.git
GIT_SYNC_BRANCH: master
GIT_SYNC_REV: HEAD
GIT_SYNC_ROOT: /opt/rosco/config/packer_custom
GIT_SYNC_USERNAME: tok-ep-sre
{{/*GIT_SYNC_PASSWORD: encrypted:k8s!n:spinnaker-github-token!k:token*/}}
```
nested under

spinnakerConfig:
# spec.spinnakerConfig.config - This section contains the contents of a deployment found in a halconfig .deploymentConfigurations[0]
config:

**Comment by ncknt** [comment]
Encrypted references are resolved in the service which is not supported by other sidecars. For the `k8s` engine though, all the operator does is mount the env var/file in the deployment. Ideally you'd have that control but I believe Halyard's config may not let you. As we move away from Halyard, you should get more of that control.

As for working around it, you could add a kustomize rule to insert the sidecar, something along the lines of:
```
kind: SpinnakerService
apiVersion: spinnaker.io/v1alpha2
...
spec:
  kustomize:
    rosco:
      patchesJson6902: |
        - op: add
          path: "/spec/template/spec/containers/-"
          value: |
            name: github-sync
            env:
              - name: GIT_SYNC_PASSWORD
                valueFrom:
                  secretKeyRef:
                    ...
```
