### ISSUE TITLE
dockerRegistryValidator detected a fatal error

### ISSUE THREAD

**Issue by sighup** [armory/spinnaker-operator#152]
We are experiencing a 401 when attempting to add a dockerRegistry account which is causing validation to fail.

```
      providers:
        dockerRegistry:                                                                                                                                                                                                                                                                             
          enabled: true
          accounts:
          - name: theregistryname
            requiredGroupMembership: []
            providerVersion: V1
            permissions: {}
            address: theregistryname.azurecr.io
            username: theregistryusername
            password: 12345ABCDEF
            email: some.email@domain.com
            cacheIntervalSeconds: 30
            clientTimeoutMillis: 60000
            cacheThreads: 4
            paginateSize: 100
            sortTagsByDate: false
            trackDigests: false
            insecureRegistry: false                                                                                                                                                                                                                             
            repositories: []
          primaryAccount: theregistryname
```


```
{"level":"info","ts":1596137498.8951218,"logger":"spinvalidate","msg":"Validator *validate.dockerRegistryValidator detected a fatal error"}
{"level":"error","ts":1596137498.895157,"logger":"spinvalidate","msg":"\nSpinnakerService validation failed:\nError with registry https://theregistryname.azurecr.io, for request 'https://theregistryname.azurecr.io/v2/': 401 HTTP status code\n"
```

Manually authenticating with the same credentials works:

```
curl -L -vv -H "Authorization: Basic $acr_credential" -H "Docker-Distribution-API-Version: registry/2.0" "https://$registry/v2"
```

```
*   Trying 40.71.10.220...
* TCP_NODELAY set
* Connected to theregistryname.azurecr.io (40.71.10.220) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=*.azurecr.io
*  start date: Jul  8 17:00:43 2020 GMT
*  expire date: Jan  8 17:00:43 2021 GMT
*  subjectAltName: host "theregistryname.azurecr.io" matched cert's "*.azurecr.io"
*  issuer: C=US; ST=Washington; L=Redmond; O=Microsoft Corporation; OU=Microsoft IT; CN=Microsoft IT TLS CA 1
*  SSL certificate verify ok.
> GET /v2 HTTP/1.1
> Host: theregistryname.azurecr.io
> User-Agent: curl/7.58.0
> Accept: */*
> Authorization: Basic <base64text>
> Docker-Distribution-API-Version: registry/2.0
> 
< HTTP/1.1 301 Moved Permanently
< Server: openresty
< Date: Thu, 30 Jul 2020 20:34:03 GMT
< Content-Type: text/html
< Content-Length: 182
< Location: https://theregistryname.azurecr.io/v2/
< Connection: keep-alive
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< 
* Ignoring the response-body
* Connection #0 to host theregistryname.azurecr.io left intact
* Issue another request to this URL: 'https://theregistryname.azurecr.io/v2/'
* Found bundle for host theregistryname.azurecr.io: 0x564a53d44360 [can pipeline]
* Re-using existing connection! (#0) with host theregistryname.azurecr.io
* Connected to theregistryname.azurecr.io (40.71.10.220) port 443 (#0)
> GET /v2/ HTTP/1.1
> Host: theregistryname.azurecr.io
> User-Agent: curl/7.58.0
> Accept: */*
> Authorization: Basic <base64text>
> Docker-Distribution-API-Version: registry/2.0
> 
< HTTP/1.1 200 OK
< Server: openresty
< Date: Thu, 30 Jul 2020 20:34:03 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 2
< Connection: keep-alive
< Access-Control-Expose-Headers: Docker-Content-Digest
< Access-Control-Expose-Headers: WWW-Authenticate
< Access-Control-Expose-Headers: Link
< Access-Control-Expose-Headers: X-Ms-Correlation-Request-Id
< Docker-Distribution-Api-Version: registry/2.0
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< X-Content-Type-Options: nosniff
< X-Ms-Correlation-Request-Id: 887e963a-3b2e-412f-af65-b2061d096a5a
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< 
* Connection #0 to host theregistryname.azurecr.io left intact
```
