### ISSUE TITLE
Air-Gapped Install Not Picking Up Private S3 for BOM

### ISSUE THREAD

**Issue by benjaques** [armory/spinnaker-operator#160]
Hello,

I am following the guide detailed here to install spinnaker w/ the operator in an air-gapped environment: https://docs.armory.io/docs/installation/guide/air-gapped/

I created my custom bucket and replicated the BOM for version 2.20.0 of armory spinnaker:

$ _aws s3 ls s3://my-bucket --endpoint-url=https://company.com_  
PRE bom/
 PRE profiles/
versions.yml

I then created a custom configmap for halyard that points to this bucket:
```
apiVersion: v1
kind: ConfigMap
data:
  halyard-local.yaml: |
    spinnaker:
      config:
        input:
          bucket: my-bucket
          enablePathStyleAccess: false
          endpoint: https://company.com
          anonymousAccess: false
```

I then mounted this configuration inside the deployment object:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spinnaker-operator
spec:
   ...
    spec:
      containers:
      - name: spinnaker-operator
        env:
        - name: AWS_ACCESS_KEY_ID
          value: xxxxx
        - name: AWS_SECRET_ACCESS_KEY
          value: xxxxx
        volumeMounts:
        - mountPath: /opt/spinnaker/config/halyard.yml
          name: halconfig-volume
          subPath: halyard-local.yaml
      - name: halyard
        env:
        - name: AWS_ACCESS_KEY_ID
          value: xxxxxx
        - name: AWS_SECRET_ACCESS_KEY
          value: xxxxxxx
        image: mydockerregistry.com/halyard:operator-7337695
        ...
        volumeMounts:
        - mountPath: /opt/spinnaker/config/halyard-local.yml
          name: halconfig-volume
          subPath: halyard-local.yaml
      ...
      volumes:
      - configMap:
          defaultMode: 420
          name: halyard-custom-config
        name: halconfig-volume

```

After deploying, I can confirm the files are placed in the correct spot:
```
k exec -it spinnaker-operator-85b54cf4cf-wk4gx -c spinnaker-operator -n spinnaker -- cat /opt/spinnaker/config/halyard.yml
spinnaker:
  config:
    input:
      bucket: my-bucket
      enablePathStyleAccess: false
      endpoint: https://company.com
      anonymousAccess: false
```

(same output for _k exec -it spinnaker-operator-85b54cf4cf-wk4gx -c halyard -n spinnaker -- cat /opt/spinner/config/halyard-local.yml_)

However, when I tail the logs for the spinnaker-operator container I see nothing but connection refused. It appears it is still trying to go outside to pull in the BOM:
_{"level":"error","ts":1597425245.8220959,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"spinnakerservice-controller","request":"spinnaker/spinnaker","error":"Unable to retrieve the Spinnaker bill of materials for version \"1.20.0\": Connection refused (Connection refused)","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/opt/spinnaker-operator/build/vendor/github.com/go-logr/zapr/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/opt/spinnaker-operator/build/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:218\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/opt/spinnaker-operator/build/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:192\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/opt/spinnaker-operator/build/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:171\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/opt/spinnaker-operator/build/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/opt/spinnaker-operator/build/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/opt/spinnaker-operator/build/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}_

I can even exec into both containers and run the aws cli command above -- I know we can reach the s3 bucket from these containers.
