### ISSUE TITLE
Spinnaker Operator for On Prem K8s

### ISSUE THREAD

**Issue by vbottu** [armory/spinnaker-operator#164]
Hi,
We are planning to deploy spinnaker on our on-prem k8s clusters and came across this operator and looks interesting. Can we use this to deploy spinnaker on-prem?

**Comment by ncknt** [comment]
Yes you can. There's no dependency on any cloud provider. If you're thinking air-gapped environment, you'll need to host bill of materials and point the operator to it but if the operator can access gcs (open source Spinnaker) or s3 (Armory Spinnaker), it should work.

**Comment by vbottu** [comment]
What kind of storage are supported for persisting the pipeline configs with the operator, with halyard we can use mysql for front50, clouddriver etc for persistence. Just wondering if the operator supports it.

**Comment by ncknt** [comment]
It should support the same configurations than Halyard does since it is still using Halyard under the cover to generate the service configuration files. It is always possible to work around any limitation by including properties in the service profiles. 

For instance, to use Front50 with SQL, I can use Redis storage in the main config (the one that Halyard inspects):

```
spec:
  spinnakerConfig:
    config:
      persistentStorage:
        persistentStoreType: redis
```

But then immediately turn it off in the profile files:

```
spec:
    ...
    profiles:      
      front50:
        spinnaker.redis.enabled: false
        sql:
          enabled: true
          ...
```

It's a bit of a kludge until we add SQL support for Front50 in Halyard (or more likely switch to Kleat).
