### ISSUE TITLE
affinity and nodeSelectors are not being applied

### ISSUE THREAD

**Issue by j771** [armory/spinnaker-operator#182]
When setting affinity or nodeSelectors in the config for the Spinnaker service like so:
```
spec:
  spinnakerConfig:
      deploymentEnvironment:
        nodeSelectors:
          some-key: some-value
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: some-key
                  operator: In
                  values:
                  - some-value
```

It does not get applied to the pods which the Spinnaker operator deploys.
