### ISSUE TITLE
kubernetes provider auth with client-go credential plugins such as azure kubelogin

### ISSUE THREAD

**Issue by jludvice** [armory/spinnaker-operator#186]
Hi, could anyone please advice how to configure kubernetes provider in a way to support
authentication with azure service principal through https://github.com/Azure/kubelogin ?

Thanks for any advice.
```
apiVersion: spinnaker.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    config:
      version: 1.22.1   # the version of Spinnaker to be deployed
      persistentStorage:
        persistentStoreType: azs
        azs:
          # ...
      providers:
        kubernetes:
          enabled: true
          accounts:
            - name: dev
              kubeconfigFile: dev-kube-config
# ...
          primaryAccount: dev
# ...
    files:
      dev-kube-config: |
        apiVersion: v1 ...
# ...
        users:
        - name:asdfasdfa
          user:
            exec:
              apiVersion: client.authentication.k8s.io/v1beta1
              args:
              - get-token
              - --environment
              - AzurePublicCloud
              - --server-id
              - asdfasdf
              - --client-id
              - asdfasdf
              - --tenant-id
              - asdasdf
              - --login
              - spn
              command: kubelogin
              env: null
```

I'm getting understandable message complaining that it can't find the `kubelogin` binary on `$PATH`
```
Resource: "spinnaker.io/v1alpha2, Resource=spinnakerservices", GroupVersionKind: "spinnaker.io/v1alpha2, Kind=SpinnakerService"
Name: "spinnaker", Namespace: "spinnaker"
for: "spinnakerservice-pepa.yml": admission webhook "webhook-spinnakerservices-v1alpha2.spinnaker.io" denied the request: 
SpinnakerService validation failed:
Validator for account 'dev' detected an error:
  error listing namespaces in account "dev":
  Get https://dev-3755ffd4.hcp.westeurope.azmk8s.io:443/api/v1/namespaces: getting credentials: exec: exec: "kubelogin": executable file not found in $PATH

```

Which pod is responsible for this validation ? 

Can it be worked around by building custom image (based on yours) and adding the `kubelogin` binary in this custom image?
