### ISSUE TITLE
Enable Microsoft Teams notifications

### ISSUE THREAD

**Issue by j771** [armory/spinnaker-operator#187]
Following this: https://spinnaker.io/setup/features/notifications/#microsoft-teams

I tried the following:

```
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    profiles:
      echo:
        echo.yml: |
          microsoftteams:
            enabled: true
```

as well as these:

```
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    profiles:
      echo:
        microsoftteams:
          enabled: true
```

```
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    profiles:
      echo:
        echo-local.yml: |
          microsoftteams:
            enabled: true
```

None of them worked.

How do you enable Teams notifications in Spinnaker with the spinnaker operator?

**Comment by cristhian-castaneda** [comment]
Hey @j771 - thanks for open the issue.
Microsoft teams support will be released on **1.23** more info [here](https://github.com/spinnaker/spinnaker/issues/5826)

**Comment by cristhian-castaneda** [comment]
When the release happens, you can update spinnaker, and the settings to activate the Microsoft Teams feature will work without a problem.

**Comment by cristhian-castaneda** [comment]
@j771 here the release calendar https://spinnaker.io/community/releases/release-cadence/#upcoming-releases

**Comment by j771** [comment]
Awesome thanks!

So will this be the correct config?
```
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    profiles:
      echo:
        echo.yml: |
          microsoftteams:
            enabled: true
```
