### ISSUE TITLE
Oauth2 for Azure not able to update sections `resource.userInfoUri` and `userInfoMapping`

### ISSUE THREAD

**Issue by j771** [armory/spinnaker-operator#190]
I am trying to update the sections `resource.userInfoUri` and `userInfoMapping` in my oauth Azure config.
The format is just like the docs specify.
https://docs.armory.io/docs/installation/operator-reference/security/#oauth2
https://spinnaker.io/setup/security/authentication/oauth/azure/#hal-config

```
  oauth2:
    client:
      accessTokenUri: 
      clientAuthenticationScheme:
      clientId: 
      clientSecret:
      preEstablishedRedirectUri: 
      scope:
      userAuthorizationUri:
    enabled:
    provider:
    resource:
      userInfoUri:
    userInfoMapping:
      email:
      firstName:
      lastName:
      userName
```

All other sections seem to be customizable but when I change the `resource.userInfoUri` and `userInfoMapping`  sections they do not update in the gate.yml
