### ISSUE TITLE
kustomise: doesn't work with service port definition

### ISSUE THREAD

**Issue by georgestack** [armory/spinnaker-operator#204]
Hello,

We are using version:
```  
spinnakerVersion: 1.19.4
  image:
    repository: gcr.io/spinnaker-marketplace/halyard
    tag: 1.32.0
```

We have noticed that when using `kustomise:` for spin-gate service, changes made on the ports: section of the service are not effective.

With below configuration it is expected that another port named test would appear in the service. 
```
      spec:
        kustomize:
          gate:
            service:
              patches:
                - |
                  metadata:
                    labels:
                      test: test
                  spec:
                    ports:
                    - name: test
                      port: 8085
                      protocol: TCP
                      targetPort: 8084
                    selector:
                      test: spinnaker
```

As a result we get:
```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-01-11T11:08:46Z"
  labels:
    app: spin
    cluster: spin-gate
    prometheus: spin-gate
  name: spin-gate
  namespace: spinnaker
  ownerReferences:
  - apiVersion: spinnaker.io/v1alpha2
    blockOwnerDeletion: true
    controller: true
    kind: SpinnakerService
    name: spinnaker
  resourceVersion: "1302293"
  selfLink: /api/v1/namespaces/spinnaker/services/spin-gate
spec:
  clusterIP: 172.20.52.42
  ports:
  - name: gate-tcp
    port: 443
    protocol: TCP
    targetPort: 8084
  selector:
    app: spin
    cluster: spin-gate
    test: spinnaker
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

even though changes using kustomize: are effective in other sections of the service like selector or labels ports are not updated. Noticed in the source code and from tested behavior that no matter what we add as port in kustomize: the ports in the service are taken by overrideBaseUrl parameter, if left empty they are chosen based on protocol (443/80):
```
apiSecurity:
    overrideBaseUrl: 
```

I believe this is a conflict of kustomize support and code, can you confirm if this is intended behavior? Why it should not be possible to add secondary service port through kustomize?

**Comment by man0s** [comment]
I was having a similar problem, I have opened the following PR: https://github.com/armory/spinnaker-operator/pull/208

**Comment by cristhian-castaneda** [comment]
@georgestack thanks for the report, and apologies for the slow response.

There is a [fix](https://github.com/armory/spinnaker-operator/pull/210) for the issue that takes the public ports based on the `overrideBaseUrl` parameter.

Now if you pass `expose.service.overrides.gate.publicPort` or `expose.service.overrides.deck.publicPort` public port should be overridden and not taken based on the overrideBaseUrl protocol.

For the kustomize part, you should use patchesStrategicMerge

**Comment by georgestack** [comment]
@cristhian-castaneda thanks a lot for the reply, we will try that, we also noticed that if we use kustomize like below, keeping the port taken as default port from overrideBaseUrl it works but makes addition of 443 obligatory. Looks like if the default port from overrideBaseUrl is missing in the definition, whole definition will be replaced in service by this port. Thanks for the support :)

```
      spec:
        kustomize:
          gate:
            service:
              patches:
                - |
                  metadata:
                    labels:
                      test: test
                  spec:
                    ports:
                    - name: gate-tcp
                      port: 443
                      protocol: TCP
                      targetPort: 8084
                    - name: test
                      port: 8085
                      protocol: TCP
                      targetPort: 8084
                    selector:
                      test: spinnaker
```
