### ISSUE TITLE
Init containers removed from spinnakerservice are not deleted

### ISSUE THREAD

**Issue by notSoWiseOldMan** [armory/spinnaker-operator#223]
### Repro steps:

1. update `spec.spinnakerConfig.kustomize` to something like:
```yaml
kustomize:
   gate:
     deployment:
       patchesStrategicMerge:
         - |
          spec:
            template:
              spec:
                containers:
                - name: gate
                initContainers:
                - name: init-sleep
                  image: busybox:latest
                  command: ['sleep', '10']

```
2. Apply changes and notice gate restarts with the init-sleep container as expected.
3. Update `spec.spinnakerConfig.kustomize` to remove the init container:
```yaml
kustomize:
   gate:
     deployment:
       patchesStrategicMerge:
         - |
          spec:
            template:
              spec:
                containers:
                - name: gate

```
**Expected Result:**
spin-gate deployment is updated to remove the init-sleep init container
spin-gate pod is restarted and init-sleep does not come up
**Actual Result:**
spin-gate deployment still contains the init-sleep init container
spin-gate pod is not restarted and init-sleep comes up on each new rollout

So far the way I have been blowing away and redeploy spinnaker and spinnaker operator all together to remove these. I have noticed the same behavior when using the `deploymentEnvironment.initContainers` properties.
