### ISSUE TITLE
[expose services] - Pods not redeployed after changing exposed ports

### ISSUE THREAD

**Issue by Lord-Y** [armory/spinnaker-operator#228]
Hi team,

Not a big deal but  let's say your first install is exposing services like bellow:

```
expose:
  type: service  # Kubernetes LoadBalancer type (service/ingress), note: only "service" is supported for now
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    # provide an override to the exposing KubernetesService
```
If you redeployed exposed services like so:
```
expose:
  type: service  # Kubernetes LoadBalancer type (service/ingress), note: only "service" is supported for now
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    # provide an override to the exposing KubernetesService
  overrides:
    deck:
      publicPort: 9000
    gate:
      publicPort: 8084
```

Go on the UI and open the browser console and you will see that a lot of requests are failing.
The solution is to delete all pods except of course the armory-spinnaker-operator-XXXX pod.
Go back to the UI, reload and everything will be back to OK.
I'm sure this issue the restart can be handle automatically when publicPort are changed.
