### ISSUE TITLE
front50 pod always crashloopbackoff

### ISSUE THREAD

**Issue by thaunggyee** [armory/spinnaker-operator#235]
```yaml
root@vm02:~# kubectl get pods -n spinnaker
NAME                                READY   STATUS             RESTARTS   AGE
spin-clouddriver-774b9444b4-zjvrh   1/1     Running            0          18m
spin-deck-8465c8f8c9-dqpql          1/1     Running            0          18m
spin-echo-765bf9ddf8-k9mkq          0/1     Running            0          18m
spin-echo-76dd4ffbfb-5j8f5          0/1     Running            0          18m
spin-front50-5474c54d48-6ss4s       0/1     CrashLoopBackOff   5          5m57s
spin-gate-7446484c5c-2lz5t          1/1     Running            0          18m
spin-orca-f6966b8d4-7m7q6           1/1     Running            0          18m
spin-redis-6777bd7cd9-wfnpv         1/1     Running            0          18m
spin-rosco-557b7888dd-48q8n         1/1     Running            0          18m
```
Hi, I deployed spinnaker with the help of your documentation. But front50 pod is always crashloopbackoff. Could you help me.

```yaml
apiVersion: spinnaker.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    config:
      version: 1.17.1   # the version of Spinnaker to be deployed
      persistentStorage:
        persistentStoreType: s3
        s3:
          bucket: <change-me> # Change to a unique name. Spinnaker stores application and pipeline definitions here
          rootFolder: front50
  # spec.expose - This section defines how Spinnaker should be publicly exposed
  expose:
    type: service  # Kubernetes LoadBalancer type (service/ingress), note: only "service" is supported for now
    service:
      type: LoadBalancer
```
Btw, can u explain me what is this s3 bucket . Can I use minio instead of s3 ?
