### ISSUE TITLE
Cannot update Spinnaker because secrets cannot be created

### ISSUE THREAD

**Issue by caongocthai** [armory/spinnaker-operator#260]
I cannot apply new SpinnakerService because the secrets that the pods mount never get created.

For example, spin-deck would mount a `spin-deck-files-xxxxx` secret like so:

```
    - name: spin-deck-files-1279982629
      secret:
        secretName: spin-deck-files-1279982629
        defaultMode: 420
```

But the secret never get created and spin-deck stuck on Pending:

```
MountVolume.SetUp failed for volume "spin-deck-files-1279982629" : secret "spin-deck-files-1279982629" not found
```
