### ISSUE TITLE
resource mapping not found for name: "spinnaker" namespace: "spinnaker" from "STDIN": no matches  for kind "SpinnakerService" in version "spinnaker.io/v1alpha2"

### ISSUE THREAD

**Issue by tirelibirefe** [armory/spinnaker-operator#264]
Hello,
This is what I do...

Installing operator:
`helm install armory-spinnaker-operator -n spinnaker-operator --wait armory/armory-spinnaker-operator`

things work; no problem.

```
$ k get crd -A | grep spinnaker
armoryaccounts.spinnaker.armory.io                    2022-08-03T23:28:51Z
spinnakerservices.spinnaker.armory.io                 2022-08-03T23:28:51Z
```

this is my spinnakerservice manifest:

```
apiVersion: spinnaker.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    config:
      version: 1.17.1   # the version of Spinnaker to be deployed
      persistentStorage:
        persistentStoreType: s3
        s3:
          bucket: $S3_BUCKET
          rootFolder: front50
          region: eu-central-1
          accessKeyId: AKIAKNLKJNLNLBLAVLA
          secretAccessKey: asdşfhUblalblbalalblawerwrwrt
  expose:
    type: service
    service:
      type: ClusterIP
```

I get the following error:

```
error: resource mapping not found for name: "spinnaker" namespace: "spinnaker" from "STDIN": no matches 
for kind "SpinnakerService" in version "spinnaker.io/v1alpha2"
ensure CRDs are installed first
```

Am I missing something? Could you please advise?

Thanks & Regards

**Comment by ichi0915** [comment]
I found a similar issue when you try to install the operator and spinnaker in a single namespace, currently working on this [Branch](https://github.com/armory/spinnaker-operator/tree/update-dependencies-and-integration-tests) to solve that, I think those changes might also solve this issue.

**Comment by tirelibirefe** [comment]
Oh thanks for your reply; is there a quick workaround which you can advise until you fix the problem?

**Comment by tirelibirefe** [comment]
I installed the operator which you referenced; now I get following error message:

`Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "webhook-spinnakerservices-v1alpha2.spinnaker.io": Post "https://spinnaker-operator.spinnaker-operator.svc:443/validate-spinnaker-io-v1alpha2-spinnakerservice?timeout=10s": Address is not allowed`

**Comment by ichi0915** [comment]
Sorry I just saw that your are using `spinnaker.armory.io`, those resources come from the armory operator not the spinnaker operator, the armory operator is an extension of the Spinnaker Operator and its on a different [repo](https://github.com/armory-io/spinnaker-operator).

Your manifest is correct you are using `apiVersion: spinnaker.io/v1alpha2` but not your operator, to install spinnaker in your current operator you should be using `apiVersion: spinnaker.armory.io/v1alpha2` and also change version to [2.27.3](https://docs.armory.io/armory-enterprise/release-notes/rn-armory-spinnaker).

when using this operator you should see this output:
```bash
$ kubectl api-resources | grep spin
spinnakeraccounts                 spinaccount   spinnaker.io/v1alpha2                  true         SpinnakerAccount
spinnakerservices                 spinsvc       spinnaker.io/v1alpha2                  true         SpinnakerService
```

**Comment by tirelibirefe** [comment]
@ichi0915 thanks for your advise. Good catch!
I think I was misunderstood. Currently I would like to go on with Armory; so I just replaced `apiVersion: spinnaker.io/v1alpha2` with `apiVersion: spinnaker.armory.io/v1alpha2` in my SpinnakerService yaml and got the following error message:

`Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "webhook-spinnakerservices-v1alpha2.spinnaker.armory.io": Post "https://spinnaker-operator.spinnaker-operator.svc:443/validate-spinnaker-armory-io-v1alpha2-spinnakerservice?timeout=10s": no endpoints available for service "spinnaker-operator"`

My current config is that;
```
$ kubectl api-resources | grep spin
armoryaccounts                    armoryaccount   spinnaker.armory.io/v1alpha2                true         ArmoryAccount
spinnakerservices                 spinsvc         spinnaker.armory.io/v1alpha2                true         SpinnakerService
```
SpinnakerService
```
apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    config:
      version: 2.27.3
      persistentStorage:
        persistentStoreType: s3
        s3:
          bucket: $S3_BUCKET
          rootFolder: front50
          region: eu-central-1
          accessKeyId: AKIAXXXXXXXXX
          secretAccessKey: xxxxxxxxxxxxxxxx
  expose:
    type: service
    service:
      type: ClusterIP
```

result:
