### ISSUE TITLE
Label Gate & Deck Ports HTTP

### ISSUE THREAD

**Issue by naturalwarren** [armory/spinnaker-operator#79]
Today Halyard doesn't label these ports. This means Gate and Deck can't work with Istio.

https://istio.io/docs/ops/configuration/traffic-management/protocol-selection/

Labeling the ports http is a canonical Kubernetes convention. Could the operator apply these labels to the services by default?

**Comment by ncknt** [comment]
Thanks @naturalwarren. Would naming all the ports for the main container work or do you need control over how they are named?
```
spec:
  ports:
  - port: 7002
    protocol: TCP
    targetPort: 7002
    name: clouddriver
```

**Comment by naturalwarren** [comment]
Naming all the ports would work. Specifically we need the service port named `http` on the Kubernetes services that serve http traffic. 

The container port does not have to be named although it would be good practice to add a name to it and have the service reference that name.

**Comment by leo-sanchez16** [comment]
Any word on an update? 
Right now im patching the services like this if anyone needs to update the name for deck and gate

`kubectl patch svc spin-deck -p '{"spec": {"ports": [{"name": "http-spin-deck","port": 9000,"protocol": "TCP","targetPort": 9000}]}}' -n YOUR_NAMESPACE
`

`kubectl patch svc spin-gate -p '{"spec": {"ports": [{"name": "http-spin-gate","port": 8084,"protocol": "TCP","targetPort": 8084}]}}' -n YOUR_NAMESPACE
`

**Comment by ncknt** [comment]
@leo-sanchez16 We added support for inline patches in the CRD: https://github.com/armory/spinnaker-operator/pull/107 (on master, `dev` release).

You can now add:
```
spec:
  kustomize:
    gate:
      service:
        patches:
        - |
          {"spec": {"ports": [{"name": "http-spin-gate","port": 8084,"protocol": "TCP","targetPort": 8084}]}}
```

or even simpler:
```
spec:
  kustomize:
    gate:
      service:
        patchesJson6902: |
          - op: replace
            path: /spec/template/spec/containers/0/ports/0/name
            value: http
```
